<a href="https://colab.research.google.com/github/dromanf/CRM/blob/master/02-numpy/02.1-Intro-to-Numpy.es.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Logo de NumPy](https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/numpy_logo.png?raw=true)

## Introducción a NumPy

`NumPy` es un juego de palabras que significa **Python numérico** (*Numerical Python*). Es una librería de código abierto que se utiliza para llevar a cabo tareas matemáticas con altísima eficiencia. Además, introduce estructuras de datos como los arrays multidimensionales, que se pueden operar entre ellos a alto nivel, sin meterse mucho en el detalle.

En concreto, las claves de esta librería son:

- **Array multidimensionales**: Esta librería proporciona un objeto llamado `ndarray`, que permite almacenar y manipular grandes conjuntos de datos de forma eficiente. Los arrays pueden tener cualquier número de dimensiones.
- **Operaciones Vectorizadas**: NumPy permite realizar operaciones matemáticas en arrays completos sin la necesidad de bucles explícitos en el código, lo que lo hace muy rápido y eficiente.
- **Funciones matemáticas**: NumPy proporciona una amplia gama de funciones matemáticas para trabajar con arrays, incluyendo funciones trigonométricas, estadísticas, álgebra lineal, entre otras.
- **Eficiencia**: Es mucho más rápido que la misma funcionalidad implementada directamente sobre Python nativo. Además, es muy flexible en términos de acceso y manipulación de elementos individuales o subconjuntos de arrays.

NumPy es una biblioteca fundamental para el Machine Learning y la ciencia de los datos en Python. Proporciona una amplia gama de herramientas y funciones para trabajar eficientemente con datos numéricos en forma de arrays y matrices.

### Arrays

Un **array** de NumPy es una estructura de datos que permite almacenar una colección de elementos, generalmente números, en una o más dimensiones.

#### Array unidimensional

Un array unidimensional (1D) de NumPy es una estructura de datos que contiene una secuencia de elementos en una única dimensión. Es similar a una lista en Python, pero con las ventajas de rendimiento y funcionalidad que ofrece NumPy.

![Array de una dimensión](https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/1D.png?raw=true "1D")

Un array 1D puede ser creado usando la función `array` de la librería con una lista de elementos como argumento. Por ejemplo:

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

Esto creará un array 1D con los elementos 1, 2, 3, 4 y 5. Los elementos del array deben ser del mismo tipo de datos. Si los elementos son de diferentes tipos, NumPy intentará convertirlos al mismo tipo si es posible.

En un array 1D, podemos acceder a los elementos usando **índices** (*indexes*), modificarlos y realizar operaciones matemáticas en el array completo de forma eficiente. A continuación se muestran algunas operaciones que se pueden realizar utilizando el array anterior:

In [ ]:
# Acceder al tercer elemento
print(array[2])

# Cambiar el valor del segundo elemento
array[1] = 7
print(array)

# Sumar 10 a todos los elementos
array += 10
print(array)

# Calcular la suma de los elementos
sum_all = np.sum(array)
print(sum_all)

3
[1 7 3 4 5]
[11 17 13 14 15]
70


#### Array N-dimensional

Un array multidimensional o n-dimensional en NumPy es una estructura de datos que organiza elementos en múltiples dimensiones (ejes). Estos arrays permiten representar estructuras de datos más complejas, como matrices (array 2D, 2 ejes), tensores (array 3D, 3 ejes) y estructuras de mayor dimensión.

![Arrays de diferentes dimensiones](https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/3D.png?raw=true "3D")

Un array N-dimensional puede ser creado también usando la función `array` de la librería. Por ejemplo, si queremos crear un array 2D:

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Si ahora quisiéramos crear un array 3D, tendríamos que pensar en él como una lista de matrices:

In [ ]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Al igual que sucedía con los arrays 1D, los elementos en un array multidimensional son accesibles mediante índices, se pueden realizar operaciones con ellos, etcétera.

A medida que agregamos más dimensiones, el principio básico sigue siendo el mismo: cada dimensión adicional puede considerarse como un nivel adicional de anidamiento. Sin embargo, a nivel práctico, trabajar con arrays de más de 3 o 4 dimensiones puede volverse más complejo y menos intuitivo.

Los arrays n-dimensionales en NumPy permiten una gran flexibilidad y potencia para representar y manipular datos en formas más complejas, especialmente útiles en campos como la ciencia de los datos, procesamiento de imágenes y aprendizaje profundo.

### Funciones

NumPy proporciona una gran cantidad de funciones predefinidas y que se pueden aplicar directamente sobre las estructuras de datos vistas anteriormente o las propias de Python (listas, matrices, etcétera). Algunas de las más utilizadas en el análisis de datos son:

In [ ]:
import numpy as np

# Crear un array para el ejemplo
arr = np.array([1, 2, 3, 4, 5])

# Operaciones Aritméticas
print("Suma:", np.add(arr, 5))
print("Producto:", np.multiply(arr, 3))

# Logarítmicas y Exponenciales
print("Logaritmo natural:", np.log(arr))
print("Exponencial:", np.exp(arr))

# Funciones Estadísticas
print("Media:", np.mean(arr))
print("Mediana:", np.median(arr))
print("Desviación estándar:", np.std(arr))
print("Varianza:", np.var(arr))
print("Máximo valor:", np.max(arr))
print("Índice del máximo valor:", np.argmax(arr))
print("Mínimo valor:", np.min(arr))
print("Índice del mínimo valor:", np.argmin(arr))
print("Suma de todos los elementos:", np.sum(arr))

# Funciones de Redondeo
arr_decimal = np.array([1.23, 2.47, 3.56, 4.89])
print("Redondeo:", np.around(arr_decimal))
print("Entero menor (floor):", np.floor(arr_decimal))
print("Entero mayor (ceil):", np.ceil(arr_decimal))

Suma: [ 6  7  8  9 10]
Producto: [ 3  6  9 12 15]
Logaritmo natural: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Exponencial: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Media: 3.0
Mediana: 3.0
Desviación estándar: 1.4142135623730951
Varianza: 2.0
Máximo valor: 5
Índice del máximo valor: 4
Mínimo valor: 1
Índice del mínimo valor: 0
Suma de todos los elementos: 15
Redondeo: [1. 2. 4. 5.]
Entero menor (floor): [1. 2. 3. 4.]
Entero mayor (ceil): [2. 3. 4. 5.]


## Ejercicios: Haz clic en "open in colab" para realizarlos

> Solución: https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/02.1-Intro-to-Numpy_solutions.ipynb

### Creación de arrays

#### Ejercicio 01:  Crea un **vector nulo** (*null vector*) que tenga 10 elementos (★☆☆)

Un vector nulo es un array de una dimensión compuesto por ceros (`0`).

> NOTA: Revisa la función `np.zeros` (https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

In [10]:
import numpy as np

# Crear un vector nulo de 10 elementos
vector_nulo = np.zeros(10)

print(vector_nulo)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Ejercicio 02: Crea un vector de unos que tenga 10 elementos (★☆☆)

> NOTA: Revisa la función `np.ones` (https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

In [11]:
vector_vacio = np.empty(10)
vector_vacio[:] = 1
print(vector_vacio)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Ejercicio 03: Investiga la función `linspace` de NumPy y crea un array que contenga 10 elementos (★☆☆)

> NOTA: Revisa la función `np.linspace` (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [12]:
import numpy as np

# Crear un vector nulo con linspace
# linspace(start, stop, num) - para que sea nulo, start y stop deben ser 0
vector_nulo = np.linspace(0, 0, 10)

print(vector_nulo)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Ejercicio 04: Busca varias formas de generar un array con números aleatorios y crea un array 1D y dos arrays 2D (★★☆)

> NOTA: Revisa las funciones `np.random.rand` (https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html), `np.random.randint` (https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html) y `np.random.randn` (https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html)

In [13]:
import numpy as np

# Semilla para resultados reproducibles
np.random.seed(42)

print("=== ARRAY 1D ===")

# 1. Con np.random.rand() - números entre 0 y 1 (distribución uniforme)
array1d_rand = np.random.rand(8)
print("1D con rand() - [0,1):", array1d_rand)

# 2. Con np.random.randint() - números enteros en un rango
array1d_randint = np.random.randint(1, 100, 8)
print("1D con randint() - [1,100):", array1d_randint)

# 3. Con np.random.randn() - distribución normal estándar (media=0, std=1)
array1d_randn = np.random.randn(8)
print("1D con randn() - N(0,1):", array1d_randn)

# 4. Con np.random.random() - similar a rand()
array1d_random = np.random.random(8)
print("1D con random() - [0,1):", array1d_random)

# 5. Con np.random.uniform() - distribución uniforme con límites personalizados
array1d_uniform = np.random.uniform(-5, 5, 8)
print("1D con uniform() - [-5,5):", array1d_uniform)

print("\n=== ARRAY 2D (PRIMERA FORMA) ===")

# Array 2D de 3x4
# 1. Con np.random.rand()
array2d_1_rand = np.random.rand(3, 4)
print("2D (3x4) con rand():")
print(array2d_1_rand)

# 2. Con np.random.randint()
array2d_1_randint = np.random.randint(0, 50, (3, 4))
print("\n2D (3x4) con randint():")
print(array2d_1_randint)

# 3. Con np.random.randn()
array2d_1_randn = np.random.randn(3, 4)
print("\n2D (3x4) con randn():")
print(array2d_1_randn)

print("\n=== ARRAY 2D (SEGUNDA FORMA) ===")

# Array 2D de 2x5
# 1. Con np.random.rand()
array2d_2_rand = np.random.rand(2, 5)
print("2D (2x5) con rand():")
print(array2d_2_rand)

# 2. Con np.random.randint()
array2d_2_randint = np.random.randint(10, 100, (2, 5))
print("\n2D (2x5) con randint():")
print(array2d_2_randint)

# 3. Con np.random.randn()
array2d_2_randn = np.random.randn(2, 5)
print("\n2D (2x5) con randn():")
print(array2d_2_randn)

print("\n=== MÉTODOS ADICIONALES ===")

# 6. Con np.random.choice() - selección de elementos de un array
array_choice = np.random.choice([1, 3, 5, 7, 9], size=6)
print("Con choice() - de lista específica:", array_choice)

# 7. Con np.random.normal() - distribución normal personalizada
array_normal = np.random.normal(loc=10, scale=2, size=6)
print("Con normal() - N(10,2):", array_normal)

# 8. Con np.random.exponential() - distribución exponencial
array_exp = np.random.exponential(scale=1.0, size=6)
print("Con exponential() - Exp(1):", array_exp)

=== ARRAY 1D ===
1D con rand() - [0,1): [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615]
1D con randint() - [1,100): [24  3 22 53  2 88 30 38]
1D con randn() - N(0,1): [ 1.46237812  1.53871497 -2.43910582  0.60344123 -0.25104397 -0.16386712
 -1.47632969  1.48698096]
1D con random() - [0,1): [0.98323089 0.46676289 0.85994041 0.68030754 0.45049925 0.01326496
 0.94220176 0.56328822]
1D con uniform() - [-5,5): [-1.14583497 -4.84033748 -2.69106174 -2.58974534  1.83263519  1.09996658
  3.33194912 -3.26635346]

=== ARRAY 2D (PRIMERA FORMA) ===
2D (3x4) con rand():
[[0.39106061 0.18223609 0.75536141 0.42515587]
 [0.20794166 0.56770033 0.03131329 0.84228477]
 [0.44975413 0.39515024 0.92665887 0.727272  ]]

2D (3x4) con randint():
[[14  7 13 22]
 [39 20 15 44]
 [17 46 23 25]]

2D (3x4) con randn():
[[ 0.09641648  0.41910211 -0.95302779 -1.0478706 ]
 [-1.87567677 -1.36678214  0.63630511 -0.90672067]
 [ 0.47604259  1.30366127  0.21158701  0.59704465]]

===

#### Ejercicio 05: Crea una matriz (array 2D) identidad de 5x5 (★☆☆)


> NOTA: Revisa la función `np.eye`(https://numpy.org/devdocs/reference/generated/numpy.eye.html)

In [14]:
import numpy as np

print("=== MÉTODO 1: np.eye() ===")
# Método más directo y eficiente
identidad1 = np.eye(5)
print("Matriz identidad 5x5 con np.eye(5):")
print(identidad1)

print("\n=== MÉTODO 2: np.identity() ===")
# Específicamente diseñada para matrices identidad
identidad2 = np.identity(5)
print("Matriz identidad 5x5 con np.identity(5):")
print(identidad2)

print("\n=== MÉTODO 3: Manual con np.zeros() y asignación ===")
# Creando manualmente
identidad3 = np.zeros((5, 5))
for i in range(5):
    identidad3[i, i] = 1
print("Matriz identidad creada manualmente:")
print(identidad3)

print("\n=== MÉTODO 4: Con np.diag() ===")
# Creando una diagonal de unos
identidad4 = np.diag([1, 1, 1, 1, 1])
print("Matriz identidad con np.diag():")
print(identidad4)

print("\n=== MÉTODO 5: Con np.ones() y manipulación ===")
# Método más creativo (pero menos eficiente)
diagonal = np.ones(5)
identidad5 = np.diagflat(diagonal)
print("Matriz identidad con np.diagflat():")
print(identidad5)

print("\n=== VERIFICACIÓN ===")
print("¿Todas las matrices son iguales?")
print("Método 1 == Método 2:", np.array_equal(identidad1, identidad2))
print("Método 1 == Método 3:", np.array_equal(identidad1, identidad3))
print("Método 1 == Método 4:", np.array_equal(identidad1, identidad4))
print("Método 1 == Método 5:", np.array_equal(identidad1, identidad5))

print("\n=== PROPIEDADES DE LA MATRIZ IDENTIDAD ===")
print("Forma (shape):", identidad1.shape)
print("Tipo de datos (dtype):", identidad1.dtype)
print("Determinante:", np.linalg.det(identidad1))
print("Traza (suma diagonal):", np.trace(identidad1))

print("\n=== COMPROBACIÓN MATRIZ IDENTIDAD ===")
# Crear un vector de prueba
vector_prueba = np.array([2, 3, 5, 7, 11])
print("Vector de prueba:", vector_prueba)
print("I × vector =", identidad1 @ vector_prueba)
print("¿I × vector == vector?", np.array_equal(identidad1 @ vector_prueba, vector_prueba))

=== MÉTODO 1: np.eye() ===
Matriz identidad 5x5 con np.eye(5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

=== MÉTODO 2: np.identity() ===
Matriz identidad 5x5 con np.identity(5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

=== MÉTODO 3: Manual con np.zeros() y asignación ===
Matriz identidad creada manualmente:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

=== MÉTODO 4: Con np.diag() ===
Matriz identidad con np.diag():
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

=== MÉTODO 5: Con np.ones() y manipulación ===
Matriz identidad con np.diagflat():
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

=== VERIFICACIÓN ===
¿Todas las matrices son iguales?
Método 1 == Método 2: True
Método 1 == Método 3: True
Método 1 == Método 4: True
Método 1 == Método 5: True

=== PROPIEDADES DE LA MATRIZ 

#### Ejercicio 06: Crea una matriz con números aleatorios de 3x2 y calcula el valor mínimo y máximo (★☆☆)

> NOTA: Revisa la función `np.min` (https://numpy.org/devdocs/reference/generated/numpy.min.html) y `np.max` (https://numpy.org/devdocs/reference/generated/numpy.max.html)

In [17]:
import numpy as np

# Semilla para resultados reproducibles
np.random.seed(123)

print("=== CREACIÓN DE MATRIZ 3x2 CON ALEATORIOS ===")

# Método 1: Con np.random.rand()
matriz_rand = np.random.rand(3, 2)
print("Matriz con rand() - [0,1):")
print(matriz_rand)

# Método 2: Con np.random.randint() - números enteros
matriz_randint = np.random.randint(1, 100, (3, 2))
print("\nMatriz con randint() - [1,100):")
print(matriz_randint)

# Método 3: Con np.random.randn() - distribución normal
matriz_randn = np.random.randn(3, 2)
print("\nMatriz con randn() - N(0,1):")
print(matriz_randn)

# Método 4: Con np.random.uniform() - rango personalizado
matriz_uniform = np.random.uniform(-10, 10, (3, 2))
print("\nMatriz con uniform() - [-10,10):")
print(matriz_uniform)

print("\n" + "="*50)
print("CÁLCULO DE MÍNIMOS Y MÁXIMOS")
print("="*50)

# Vamos a trabajar principalmente con la matriz de randint por ser más legible
matriz = matriz_randint
print("Matriz de trabajo (randint):")
print(matriz)

print("\n=== VALOR MÍNIMO ===")
# Diferentes formas de calcular el mínimo
minimo1 = np.min(matriz)
minimo2 = matriz.min()
minimo3 = np.amin(matriz)  # alias de np.min

print(f"np.min(matriz): {minimo1}")
print(f"matriz.min(): {minimo2}")
print(f"np.amin(matriz): {minimo3}")

print("\n=== VALOR MÁXIMO ===")
# Diferentes formas de calcular el máximo
maximo1 = np.max(matriz)
maximo2 = matriz.max()
maximo3 = np.amax(matriz)  # alias de np.max

print(f"np.max(matriz): {maximo1}")
print(f"matriz.max(): {maximo2}")
print(f"np.amax(matriz): {maximo3}")

print("\n=== MÍNIMOS Y MÁXIMOS POR EJES (FILAS Y COLUMNAS) ===")
# Mínimos por filas (eje 1) - mínimo de cada fila
minimos_filas = np.min(matriz, axis=1)
print(f"Mínimos por filas (axis=1): {minimos_filas}")

# Mínimos por columnas (eje 0) - mínimo de cada columna
minimos_columnas = np.min(matriz, axis=0)
print(f"Mínimos por columnas (axis=0): {minimos_columnas}")

# Máximos por filas (eje 1) - máximo de cada fila
maximos_filas = np.max(matriz, axis=1)
print(f"Máximos por filas (axis=1): {maximos_filas}")

# Máximos por columnas (eje 0) - máximo de cada columna
maximos_columnas = np.max(matriz, axis=0)
print(f"Máximos por columnas (axis=0): {maximos_columnas}")

print("\n=== POSICIÓN DE LOS VALORES MÍNIMO Y MÁXIMO ===")
# Encontrar la posición (índice) del valor mínimo
pos_minimo = np.argmin(matriz)
pos_minimo_fila, pos_minimo_columna = np.unravel_index(np.argmin(matriz), matriz.shape)

# Encontrar la posición (índice) del valor máximo
pos_maximo = np.argmax(matriz)
pos_maximo_fila, pos_maximo_columna = np.unravel_index(np.argmax(matriz), matriz.shape)

print(f"Posición lineal del mínimo: {pos_minimo}")
print(f"Posición (fila, columna) del mínimo: ({pos_minimo_fila}, {pos_minimo_columna})")
print(f"Posición lineal del máximo: {pos_maximo}")
print(f"Posición (fila, columna) del máximo: ({pos_maximo_fila}, {pos_maximo_columna})")

print("\n=== COMPROBACIÓN CON TODAS LAS MATRICES ===")
matrices = {
    "rand() [0,1)": matriz_rand,
    "randint() [1,100)": matriz_randint,
    "randn() N(0,1)": matriz_randn,
    "uniform() [-10,10)": matriz_uniform
}

for nombre, matriz in matrices.items():
    min_val = np.min(matriz)
    max_val = np.max(matriz)
    print(f"{nombre:20} -> Mínimo: {min_val:8.4f}, Máximo: {max_val:8.4f}")

=== CREACIÓN DE MATRIZ 3x2 CON ALEATORIOS ===
Matriz con rand() - [0,1):
[[0.69646919 0.28613933]
 [0.22685145 0.55131477]
 [0.71946897 0.42310646]]

Matriz con randint() - [1,100):
[[87 98]
 [97 48]
 [74 33]]

Matriz con randn() - N(0,1):
[[ 1.26593626 -0.8667404 ]
 [-0.67888615 -0.09470897]
 [ 1.49138963 -0.638902  ]]

Matriz con uniform() - [-10,10):
[[-6.35016539 -6.49096488]
 [ 0.63102748  0.63655174]
 [ 2.68801917  6.98863588]]

CÁLCULO DE MÍNIMOS Y MÁXIMOS
Matriz de trabajo (randint):
[[87 98]
 [97 48]
 [74 33]]

=== VALOR MÍNIMO ===
np.min(matriz): 33
matriz.min(): 33
np.amin(matriz): 33

=== VALOR MÁXIMO ===
np.max(matriz): 98
matriz.max(): 98
np.amax(matriz): 98

=== MÍNIMOS Y MÁXIMOS POR EJES (FILAS Y COLUMNAS) ===
Mínimos por filas (axis=1): [87 48 33]
Mínimos por columnas (axis=0): [74 33]
Máximos por filas (axis=1): [98 97 74]
Máximos por columnas (axis=0): [97 98]

=== POSICIÓN DE LOS VALORES MÍNIMO Y MÁXIMO ===
Posición lineal del mínimo: 5
Posición (fila, columna) del 

#### Ejercicio 07: Crea un vector con números aleatorios de 30 elementos y calcula la media (★☆☆)

> NOTA: Revisa la función `np.mean` (https://numpy.org/doc/stable/reference/generated/numpy.mean.html)

In [18]:
import numpy as np

# Semilla para resultados reproducibles
np.random.seed(42)

print("=== CREACIÓN DE VECTOR CON 30 ELEMENTOS ALEATORIOS ===")

# Método 1: Con np.random.rand() - números entre 0 y 1
vector_rand = np.random.rand(30)
print("Vector con rand() - [0,1):")
print(vector_rand)

# Método 2: Con np.random.randint() - números enteros
vector_randint = np.random.randint(1, 101, 30)  # Números entre 1 y 100
print("\nVector con randint() - [1,101):")
print(vector_randint)

# Método 3: Con np.random.randn() - distribución normal
vector_randn = np.random.randn(30)
print("\nVector con randn() - N(0,1):")
print(vector_randn)

# Método 4: Con np.random.uniform() - rango personalizado
vector_uniform = np.random.uniform(-5, 5, 30)
print("\nVector con uniform() - [-5,5):")
print(vector_uniform)

print("\n" + "="*60)
print("CÁLCULO DE LA MEDIA")
print("="*60)

# Vamos a trabajar con el vector de randint por ser más interpretable
vector = vector_randint
print("Vector de trabajo (randint):")
print(vector)

print("\n=== CÁLCULO DE LA MEDIA - DIFERENTES MÉTODOS ===")

# Método 1: np.mean() - función universal de NumPy
media1 = np.mean(vector)
print(f"np.mean(vector): {media1:.4f}")

# Método 2: array.mean() - método del objeto array
media2 = vector.mean()
print(f"vector.mean(): {media2:.4f}")

# Método 3: Cálculo manual - suma todos los elementos y divide por el número de elementos
media_manual = np.sum(vector) / len(vector)
print(f"Cálculo manual (sum/len): {media_manual:.4f}")

# Método 4: Usando statistics.mean() (de la librería estándar)
import statistics
media_stats = statistics.mean(vector)
print(f"statistics.mean(vector): {media_stats:.4f}")

print("\n=== VERIFICACIÓN DE RESULTADOS ===")
print(f"¿np.mean == vector.mean? {np.isclose(media1, media2)}")
print(f"¿np.mean == cálculo manual? {np.isclose(media1, media_manual)}")
print(f"¿np.mean == statistics.mean? {np.isclose(media1, media_stats)}")

print("\n=== PROPIEDADES ESTADÍSTICAS ADICIONALES ===")
# Otras medidas estadísticas importantes
mediana = np.median(vector)
moda = statistics.mode(vector) if len(set(vector)) == len(vector) else "No hay moda única"
desviacion_estandar = np.std(vector)
varianza = np.var(vector)

print(f"Mediana: {mediana:.4f}")
try:
    print(f"Moda: {moda}")
except:
    print("No hay moda única")
print(f"Desviación estándar: {desviacion_estandar:.4f}")
print(f"Varianza: {varianza:.4f}")
print(f"Rango: {np.ptp(vector)}")
print(f"Mínimo: {np.min(vector)}")
print(f"Máximo: {np.max(vector)}")

print("\n=== MEDIA DE TODOS LOS VECTORES ===")
vectores = {
    "rand() [0,1)": vector_rand,
    "randint() [1,101)": vector_randint,
    "randn() N(0,1)": vector_randn,
    "uniform() [-5,5)": vector_uniform
}

for nombre, vec in vectores.items():
    media = np.mean(vec)
    mediana = np.median(vec)
    print(f"{nombre:20} -> Media: {media:8.4f}, Mediana: {mediana:8.4f}")

print("\n=== CÁLCULOS DE MEDIA CON CONDICIONES ===")
# Media de elementos mayores que un valor umbral
umbral = 50
elementos_mayores_umbral = vector[vector > umbral]
if len(elementos_mayores_umbral) > 0:
    media_mayores = np.mean(elementos_mayores_umbral)
    print(f"Media de elementos > {umbral}: {media_mayores:.4f} ({len(elementos_mayores_umbral)} elementos)")
else:
    print(f"No hay elementos mayores que {umbral}")

# Media de elementos pares e impares
elementos_pares = vector[vector % 2 == 0]
elementos_impares = vector[vector % 2 == 1]

if len(elementos_pares) > 0:
    media_pares = np.mean(elementos_pares)
    print(f"Media de elementos pares: {media_pares:.4f} ({len(elementos_pares)} elementos)")

if len(elementos_impares) > 0:
    media_impares = np.mean(elementos_impares)
    print(f"Media de elementos impares: {media_impares:.4f} ({len(elementos_impares)} elementos)")

print("\n=== MEDIA PONDERADA ===")
# Crear pesos aleatorios para el vector
pesos = np.random.rand(30)
pesos = pesos / np.sum(pesos)  # Normalizar para que sumen 1

media_ponderada = np.average(vector, weights=pesos)
print(f"Media ponderada: {media_ponderada:.4f}")

print("\n=== COMPARACIÓN: MEDIA vs MEDIA RECORTADA ===")
# Media recortada (excluye valores extremos)
media_recortada = statistics.mean(sorted(vector)[5:25])  # Excluye 5 valores por extremo
print(f"Media normal: {media1:.4f}")
print(f"Media recortada (excluyendo 5 valores por extremo): {media_recortada:.4f}")

print("\n=== VISUALIZACIÓN DE LA DISTRIBUCIÓN ===")
# Información sobre la distribución
print(f"Número de elementos: {len(vector)}")
print(f"Suma total: {np.sum(vector)}")
print(f"Media teórica esperada (para uniforme [1,100]): {(1 + 100) / 2}")

# Frecuencia de valores
valores_unicos, conteos = np.unique(vector, return_counts=True)
valor_mas_frecuente = valores_unicos[np.argmax(conteos)]
print(f"Valor más frecuente: {valor_mas_frecuente} (aparece {conteos.max()} veces)")

print("\n=== EJEMPLO PRÁCTICO: ANÁLISIS DE CALIFICACIONES ===")
# Ejemplo práctico: análisis de calificaciones
calificaciones = np.random.randint(0, 11, 30)  # Calificaciones de 0 a 10
print("Vector de calificaciones (0-10):")
print(calificaciones)

media_calificaciones = np.mean(calificaciones)
aprobados = np.sum(calificaciones >= 5)
porcentaje_aprobados = (aprobados / len(calificaciones)) * 100

print(f"Media de calificaciones: {media_calificaciones:.2f}")
print(f"Aprobados (≥5): {aprobados}/{len(calificaciones)} ({porcentaje_aprobados:.1f}%)")
print(f"Calificación más alta: {np.max(calificaciones)}")
print(f"Calificación más baja: {np.min(calificaciones)}")

=== CREACIÓN DE VECTOR CON 30 ELEMENTOS ALEATORIOS ===
Vector con rand() - [0,1):
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643
 0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184
 0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]

Vector con randint() - [1,101):
[51  7 21 73 39 18  4 89 60 14  9 90 53  2 84 92 60 71 44  8 47 35 78 81
 36 50  4  2  6 54]

Vector con randn() - N(0,1):
[-1.32818605  0.19686124  0.73846658  0.17136828 -0.11564828 -0.3011037
 -1.47852199 -0.71984421 -0.46063877  1.05712223  0.34361829 -1.76304016
  0.32408397 -0.38508228 -0.676922    0.61167629  1.03099952  0.93128012
 -0.83921752 -0.30921238  0.33126343  0.97554513 -0.47917424 -0.18565898
 -1.10633497 -1.19620662  0.81252582  1.35624003 -0.07201012  1.0035329 ]

Vector con uniform() - [-5,5):
[-3.80405754  2.13244787  2.6

#### Ejercicio 08: Convierte la lista `[1, 2, 3]` y la tupla `(1, 2, 3)` en arrays (★☆☆)

### Operaciones entre arrays

#### Ejercicio 09: Invierte el vector del ejercicio anterior (★☆☆)

> NOTA: Revisa la función `np.flip` (https://numpy.org/doc/stable/reference/generated/numpy.flip.html)

#### Ejercicio 10: Cambia el tamaño de un array aleatorio de dimensiones 5x12 en 12x5 (★☆☆)

> NOTA: Revisa la función `np.reshape` (https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

#### Ejercicio 11: Convierte la lista `[1, 2, 0, 0, 4, 0]` en un array y obtén el índice de los elementos que no son cero (★★☆)

> NOTA: Revisa la función `np.where` (https://numpy.org/devdocs/reference/generated/numpy.where.html)

#### Ejercicio 12: Convierte la lista `[0, 5, -1, 3, 15]` en un array, multiplica sus valores por `-2` y obtén los elementos pares (★★☆)

#### Ejercicio 13: Crea un vector aleatorio de 10 elementos y ordénalo de menor a mayor (★★☆)

> NOTA: Revisa la función `np.sort` (https://numpy.org/doc/stable/reference/generated/numpy.sort.html)

#### Ejercicio 14: Genera dos vectores aleatorios de 8 elementos y aplica las operaciones de suma, resta y multiplicación entre ellos (★★☆)

> NOTA: Revisa las funciones matemáticas: https://numpy.org/doc/stable/reference/routines.math.html

#### Ejercicio 15: Convierte la lista `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]` en un array y transfórmalo en una matriz con filas de 3 columnas (★★★)